"use client"
import React, { useState, useEffect } from "react"
import { usePathname } from "next/navigation"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/css/globals.css";
const img = 'logoIRISI-White.png';
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const [isLoading, setIsLoading] = useState(true)

	useEffect(() => {
		if (isLoading) {
			return
		}
	}, [isLoading])

	const handleFinishLoading = () => {
		// Your logic when loading finishes
		setIsLoading(false);
	};


	return (
		<html lang="en">
			<body className={inter.className}>
					<div
						className="mx-auto grid h-full min-h-screen"
						style={{
							gridTemplateColumns: "100%",
							gridTemplateRows: "auto 1fr auto",
						}}
					>
						<header className="container sticky top-0 z-40  mx-auto">
							<div style={{boxShadow: "0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)", padding: "5px", marginBottom: "10px" }} className="border-b border-b-slate-200 py-4">
								<nav className="my-2 pl-6 ">
									<center>
										<a href="#" className="hover:text-slate-600 cursor-pointer">
											<img className="object-cover h-20" src={img} alt='header-img' />
										</a>
									</center>
								</nav>
							</div>
						</header>
						<main className="flex w-full h-full flex-1 flex-col overflow-hidden">
							{children}
						</main>
						<footer style={{ color: "#ffffff", boxShadow: "0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)", border: "1px solid #ffffff", padding: "5px", marginBottom: "10px" }} className="m-auto p-4">
							By Abdelhadi El Bcir & Younnes Serrakhi.
						</footer>
					</div>
			</body>
		</html>
	);
}
